theme: jekyll-theme-minimal
title: David Hubbard's blog
description: The custom theme in _layouts/ should have hidden this. Broken site!
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
